#### YAML workflow to initiate linting, typechecking & testing on commit

name: Commit
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy
          pip install -r requirements.txt
      - name: Lint with flake8
        run: make lint
      - name: typecheck with mypy
        run: make typecheck
      - name: Test with pytest
        run: make test
